/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as DemandesIndexRouteImport } from './routes/demandes.index'
import { Route as DemandesNouvelleRouteImport } from './routes/demandes.nouvelle'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesNouvelleRoute = DemandesNouvelleRouteImport.update({
  id: '/demandes/nouvelle',
  path: '/demandes/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/demandes/nouvelle': typeof DemandesNouvelleRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/demandes/': typeof DemandesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/demandes/nouvelle': typeof DemandesNouvelleRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/demandes': typeof DemandesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/demandes/nouvelle': typeof DemandesNouvelleRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/demandes/': typeof DemandesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/contact'
    | '/tableau-de-bord'
    | '/actualites/$slug'
    | '/demandes/nouvelle'
    | '/services/$slug'
    | '/actualites/'
    | '/demandes/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/contact'
    | '/tableau-de-bord'
    | '/actualites/$slug'
    | '/demandes/nouvelle'
    | '/services/$slug'
    | '/actualites'
    | '/demandes'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/contact'
    | '/tableau-de-bord'
    | '/actualites/$slug'
    | '/demandes/nouvelle'
    | '/services/$slug'
    | '/actualites/'
    | '/demandes/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  DemandesNouvelleRoute: typeof DemandesNouvelleRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/nouvelle': {
      id: '/demandes/nouvelle'
      path: '/demandes/nouvelle'
      fullPath: '/demandes/nouvelle'
      preLoaderRoute: typeof DemandesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  DemandesNouvelleRoute: DemandesNouvelleRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  DemandesIndexRoute: DemandesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
